version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./default.conf:/etc/nginx/conf.d/default.conf
